// <auto-generated />
using System;
using BelgradeATC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BelgradeATC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328002151_AddParkingSpotSeed")]
    partial class AddParkingSpotSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BelgradeATC.Core.Entities.Aircraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Altitude")
                        .HasColumnType("integer");

                    b.Property<string>("CallSign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Heading")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CallSign")
                        .IsUnique();

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("BelgradeATC.Core.Entities.ParkingSpot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OccupiedBy")
                        .HasColumnType("text");

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f3c9d2-7b4e-4c1a-9f2e-1a2b3c4d5e01"),
                            SpotNumber = "A1",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b2e4d1c3-8c5f-4d2b-a1f3-2b3c4d5e6f02"),
                            SpotNumber = "A2",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("c3d5e2f4-9d6a-4e3c-b2e4-3c4d5e6f7a03"),
                            SpotNumber = "A3",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d4e6f3a5-af7b-4f4d-c3d5-4d5e6f7a8b04"),
                            SpotNumber = "A4",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e5f7a4b6-b08c-405e-d4e6-5e6f7a8b9c05"),
                            SpotNumber = "A5",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("f6a8b5c7-c19d-416f-e5f7-6f7a8b9c0d06"),
                            SpotNumber = "P1",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("07b9c6d8-d2ae-4270-f6a8-7a8b9c0d1e07"),
                            SpotNumber = "P2",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("18cad7e9-e3bf-4381-a7b9-8b9c0d1e2f08"),
                            SpotNumber = "P3",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("29dbe8fa-f4c0-4492-b8ca-9c0d1e2f3a09"),
                            SpotNumber = "P4",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("3aecf90b-05d1-45a3-c9db-0d1e2f3a4b10"),
                            SpotNumber = "P5",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("4bfd0a1c-16e2-46b4-daec-1e2f3a4b5c11"),
                            SpotNumber = "P6",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("5c0e1b2d-27f3-47c5-ebfd-2f3a4b5c6d12"),
                            SpotNumber = "P7",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("6d1f2c3e-3804-48d6-fc0e-3a4b5c6d7e13"),
                            SpotNumber = "P8",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("7e203d4f-4915-49e7-0d1f-4b5c6d7e8f14"),
                            SpotNumber = "P9",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("8f314e50-5a26-4af8-1e20-5c6d7e8f9015"),
                            SpotNumber = "P10",
                            Type = 1
                        });
                });

            modelBuilder.Entity("BelgradeATC.Core.Entities.StateChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AircraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("RequestedState")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("StateChangeLogs");
                });

            modelBuilder.Entity("BelgradeATC.Core.Entities.StateChangeLog", b =>
                {
                    b.HasOne("BelgradeATC.Core.Entities.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");

                    b.Navigation("Aircraft");
                });
#pragma warning restore 612, 618
        }
    }
}
